import React from "react";
import "./Features.css";

function Features() {
  return (
    <div id="Features">
      <div className="Features_main_div">
        <h1 className="Features_main_div_heading">Features</h1>

        <div className="container Features_container">
          <div className="row Features_main_div_row res_green_fst">
            <div className="col-lg-1"></div>
            <div className="col-lg-4">
              <div className="green_box res_green">
                <div className="l_box">
                  <div className="small_green_box">
                    <span>L</span>
                  </div>
                </div>
                <h4>Launchpad</h4>
                <p>
                  Pepe Incubator is proud to offer an exclusive launchpad for
                  meme-based projects. Our launchpad applies a whitelist system,
                  ensuring that only selected projects and individuals who have
                  been whitelisted can launch on Pepe Incubator. This approach
                  allows us to maintain a high level of quality and ensure that
                  our community members have access to the best and most
                  innovative projects.{" "}
                </p>
              </div>
            </div>
            <div className="col-lg-1"></div>

            <div className="col-lg-4">
              <div className="green_box res_green">
                <div className="l_box">
                  <div className="small_green_box">
                    <span>F</span>
                  </div>
                </div>
                <h4>Funding</h4>
                <p>
                  Pepe Incubator is dedicated to supporting innovative
                  meme-based projects by providing funding and investment
                  opportunities. Our goal is to help projects succeed and
                  thrive, while also benefiting our community and fostering the
                  growth of new and innovative projects. By joining Pepe
                  Incubator, you'll have access to a wealth of resources and
                  support, including funding, mentorship, and networking
                  opportunities.
                </p>
              </div>
            </div>
          </div>

          <div className="row Features_main_div_row">
            <div className="col-lg-1"></div>
            <div className="col-lg-4">
              <div className="green_box res_green">
                <div className="l_box">
                  <div className="small_green_box">
                    <span>D</span>
                  </div>
                </div>
                <h4>Deflationary</h4>
                <p>
                  Pepe Incubator is an innovative platform that operates within
                  a deflationary ecosystem. As part of its unique model, the
                  revenue generated by Pepe Incubator will be allocated towards
                  the strategic initiative of buying back and subsequently
                  burning $PEPEINC tokens. This approach not only helps to
                  create scarcity, but also enhances the overall value
                  proposition of the token, benefiting token holders and
                  fostering a sustainable ecosystem.
                </p>
              </div>
            </div>
            <div className="col-lg-1"></div>

            <div className="col-lg-4">
              <div className="green_box res_green">
                <div className="l_box">
                  <div className="small_green_box">
                    <span>D</span>
                  </div>
                </div>
                <h4>DAPPS</h4>
                <p>
                  Pepe Incubator provides a variety of DApps that generate
                  revenue, including a token generator and launchpad. These
                  innovative applications offer users the chance to participate
                  in token creation, fostering the growth and sustainability of
                  the Pepe Incubator ecosystem. Through these powerful DApps,
                  individuals can engage in the creation, distribution, and
                  exchange of tokens, contributing to the overall vibrancy and
                  economic potential of the platform.
                </p>
              </div>
            </div>
          </div>
        </div>

        
      </div>
    </div>
  );
}

export default Features;
